quarkus.datasource.db-kind=postgresql

%prod.quarkus.datasource.reactive.url=postgresql://localhost:5432/telemetry_db
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus

quarkus.hibernate-orm.database.generation=drop-and-create
kafka.bootstrap.servers=localhost:9092
